name: sign_vision_app
description: "Sign Vision - Sign Language Translation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  http: ^1.2.2
  http_parser: ^4.1.0
  video_player: ^2.9.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
